name: example
description: A project that showcases usage of swagger_parser
publish_to: none
environment:
  sdk: '>=3.2.0 <4.0.0'

dependencies:
  dart_mappable: ^4.2.2
  dio: ^5.4.3+1
  freezed_annotation: ^2.4.1
  json_annotation: ^4.9.0
  retrofit: ^4.1.0

dev_dependencies:
  build_runner: ^2.4.11
  carapacik_lints: ^1.6.0
  dart_mappable_builder: ^4.2.3
  freezed: ^2.5.2
  json_serializable: ^6.8.0
  retrofit_generator: ^8.1.0
  swagger_parser:
    path:
      ../
